.PHONY: run setup openapi/generate

setup:
	@command -v openapi-generator >/dev/null 2>&1 || brew install openapi-generator;
	@which -a goimports >/dev/null 2>&1 || go install golang.org/x/tools/cmd/goimports@latest;

openapi/generate: openapi-server openapi-client
	@echo "OpenAPI files generated"
openapi-server:
	rm -rf go/autogenerated_api
	openapi-generator generate -i ./openapi.yaml -g go-server -o ./go/autogenerated_api \
	--additional-properties=packageName=autogenerated_api,outputAsLibrary=true,router=chi,generateInterfaces=true,sourceFolder=""
	$$(go env GOPATH)/bin/goimports -w ./go/autogenerated_api

openapi-client:
	rm -rf go/autogenerated_client
	openapi-generator generate -i ./openapi.yaml -g go -o ./go/autogenerated_client \
	--additional-properties=packageName=autogenerated_client,outputAsLibrary=true,generateInterfaces=true,sourceFolder="" \
	--ignore-file-override .openapi-client-ignore

build:
	go build -C go -o bin/ .

run:
	go run -C go main.go

test/setup:
	@which -a ginkgo > /dev/null || go install github.com/onsi/ginkgo/v2/ginkgo@v2.22.1

test: test/setup
	go test -C go ./...
