.PHONY: run setup openapi/generate

setup:
	@command -v openapi-generator >/dev/null 2>&1 || brew install openapi-generator;
	@which -a goimports >/dev/null 2>&1 || go install golang.org/x/tools/cmd/goimports@latest;

openapi-generate:
	rm -rf go/api
	openapi-generator generate -i ./openapi.yaml -g go-server -o ./go/autogenerated_api \
	--additional-properties=packageName=autogenerated_api,outputAsLibrary=true,router=chi,generateInterfaces=true,sourceFolder=""
	$$(go env GOPATH)/bin/goimports -w ./go/autogenerated_api

build:
	go build -C go -o bin/ .

run:
	go run -C go main.go

test:
	go test -C go ./...