openapi: 3.0.0
info:
  title: Sieve of Eratosthenes API
  description: This api does one thing and one thing only, get you a prime by number.
  version: 1.0.0

servers:

  - url: http://localhost:8080
    description: localhost server
paths:
  /primebynumber/{nthprime}:
    get:
      tags: [Eratosthenes]
      summary: Retrieve nth prime number
      description: Returns the nth prime number based on the provided path variable. The 0th prime is 2
      operationId: getNthPrime
      parameters:
        - name: nthprime
          in: path
          required: true
          schema:
            type: integer
            format: int64
            example: 10
            minimum: 0
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                required:
                  - prime
                properties:
                  prime:
                    type: integer
                    format: int64
                    example: 29
                    minimum: 0
        "400":
          description: Bad Request - must be a number.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "nthprime value must be >= 0"
