openapi: 3.0.0
info:
  description: "This api does one thing and one thing only, get you a prime by number."
  title: Sieve of Eratosthenes API
  version: 1.0.0
servers:
- description: localhost server
  url: http://localhost:8080
paths:
  /primebynumber/{nthprime}:
    get:
      description: Returns the nth prime number based on the provided path variable.
        The 0th prime is 2
      operationId: getNthPrime
      parameters:
      - explode: false
        in: path
        name: nthprime
        required: true
        schema:
          example: 10
          format: int64
          minimum: 0
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getNthPrime_200_response'
          description: Successful response
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getNthPrime_400_response'
          description: Bad Request - must be a number.
      summary: Retrieve nth prime number
      tags:
      - Eratosthenes
components:
  schemas:
    getNthPrime_200_response:
      example:
        prime: 29
      properties:
        prime:
          example: 29
          format: int64
          minimum: 0
          type: integer
      required:
      - prime
      type: object
    getNthPrime_400_response:
      example:
        error: nthprime value must be >= 0
      properties:
        error:
          example: nthprime value must be >= 0
          type: string
      type: object
