package main

import (
	"log"
	"net/http"
	"ssse-exercise-sieve/autogenerated_api"
	"ssse-exercise-sieve/sieve_api"
)

func main() {
	// start the api
	sieveService := sieve_api.NewDefaultAPIService()

	sieveClient := autogenerated_api.NewDefaultAPIController(sieveService)
	router := autogenerated_api.NewRouter(sieveClient)
	// Start the server
	log.Println("Starting API server on http://localhost:8080")
	log.Println("test me out! http://localhost:8080/primebynumber/1000")
	if err := http.ListenAndServe(":8080", router); err != nil {
		log.Fatalf("Server failed to start: %v", err)
	}
}
