// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Sieve of Eratosthenes API
 *
 * This api does one thing and one thing only, get you a prime by number.
 *
 * API version: 1.0.0
 */

package autogenerated_api

import (
	"net/http"
	"strings"

	"github.com/go-chi/chi/v5"
)

// EratosthenesAPIController binds http requests to an api service and writes the service results to the http response
type EratosthenesAPIController struct {
	service      EratosthenesAPIServicer
	errorHandler ErrorHandler
}

// EratosthenesAPIOption for how the controller is set up.
type EratosthenesAPIOption func(*EratosthenesAPIController)

// WithEratosthenesAPIErrorHandler inject ErrorHandler into controller
func WithEratosthenesAPIErrorHandler(h ErrorHandler) EratosthenesAPIOption {
	return func(c *EratosthenesAPIController) {
		c.errorHandler = h
	}
}

// NewEratosthenesAPIController creates a default api controller
func NewEratosthenesAPIController(s EratosthenesAPIServicer, opts ...EratosthenesAPIOption) *EratosthenesAPIController {
	controller := &EratosthenesAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the EratosthenesAPIController
func (c *EratosthenesAPIController) Routes() Routes {
	return Routes{
		"GetNthPrime": Route{
			strings.ToUpper("Get"),
			"/primebynumber/{nthprime}",
			c.GetNthPrime,
		},
	}
}

// GetNthPrime - Retrieve nth prime number
func (c *EratosthenesAPIController) GetNthPrime(w http.ResponseWriter, r *http.Request) {
	nthprimeParam, err := parseNumericParameter[int64](
		chi.URLParam(r, "nthprime"),
		WithRequire[int64](parseInt64),
		WithMinimum[int64](0),
	)
	if err != nil {
		c.errorHandler(w, r, &ParsingError{Param: "nthprime", Err: err}, nil)
		return
	}
	result, err := c.service.GetNthPrime(r.Context(), nthprimeParam)
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	_ = EncodeJSONResponse(result.Body, &result.Code, w)
}
