// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Sieve of Eratosthenes API
 *
 * This api does one thing and one thing only, get you a prime by number.
 *
 * API version: 1.0.0
 */

package autogenerated_api

import (
	"context"
	"errors"
	"net/http"
)

// DefaultAPIService is a service that implements the logic for the DefaultAPIServicer
// This service should implement the business logic for every endpoint for the DefaultAPI API.
// Include any external packages or services that will be required by this service.
type DefaultAPIService struct {
}

// NewDefaultAPIService creates a default api service
func NewDefaultAPIService() *DefaultAPIService {
	return &DefaultAPIService{}
}

// GetNthPrime - Retrieve nth prime number
func (s *DefaultAPIService) GetNthPrime(ctx context.Context, nthprime int64) (ImplResponse, error) {
	// TODO - update GetNthPrime with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, GetNthPrime200Response{}) or use other options such as http.Ok ...
	// return Response(200, GetNthPrime200Response{}), nil

	// TODO: Uncomment the next line to return response Response(400, GetNthPrime400Response{}) or use other options such as http.Ok ...
	// return Response(400, GetNthPrime400Response{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetNthPrime method not implemented")
}
