// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Sieve of Eratosthenes API
 *
 * This api does one thing and one thing only, get you a prime by number.
 *
 * API version: 1.0.0
 */

package autogenerated_api

type GetNthPrime400Response struct {
	Error string `json:"error,omitempty"`
}

// AssertGetNthPrime400ResponseRequired checks if the required fields are not zero-ed
func AssertGetNthPrime400ResponseRequired(obj GetNthPrime400Response) error {
	return nil
}

// AssertGetNthPrime400ResponseConstraints checks if the values respects the defined constraints
func AssertGetNthPrime400ResponseConstraints(obj GetNthPrime400Response) error {
	return nil
}
